name: ICS-OS CI

on:
  workflow_dispatch:
    branches: [ "development", "master" ]
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential nasm qemu-kvm tcc git gcc-multilib sudo

    - name: Compile and create floppy image
      run: make -C ics-os/ all

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ics-os.${{ github.sha }}
        path: ics-os/ics-os-floppy.img
